{{--
    Quarterly retrospective PDF template.

    Thin wrapper around the shared _partials.blade.php — same sections
    as the annual report scoped to a single fiscal quarter, with cover
    page copy adjusted and the comparison block labelled
    quarter-over-quarter.
--}}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Quarterly Wallet Report - {{ $corpName }}</title>
<style>
    @page { margin: 1.5cm 1.5cm 2cm 1.5cm; }
    body { font-family: 'DejaVu Sans', sans-serif; font-size: 10pt; color: #333; line-height: 1.4; }
    h1 { color: #667eea; font-size: 22pt; margin: 0 0 8px 0; }
    h2 { color: #667eea; font-size: 13pt; margin: 18px 0 8px 0; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
    h3 { color: #555;    font-size: 11pt; margin: 14px 0 6px 0; }
    .meta { color: #666; font-size: 9pt; margin-bottom: 16px; }
    .meta div { margin: 2px 0; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 8px; }
    th, td { border: 1px solid #ddd; padding: 5px 8px; text-align: left; font-size: 9pt; vertical-align: middle; }
    th { background: #f0f4f8; font-weight: bold; color: #555; }
    td.num, th.num { text-align: right; font-family: 'DejaVu Sans Mono', monospace; }
    td.desc { font-size: 8pt; color: #666; }
    .summary-grid td { border: 0; padding: 4px 0; }
    .pill { display: inline-block; padding: 2px 8px; border-radius: 8px; font-size: 8pt; font-weight: bold; color: #fff; }
    .pill-high { background: #e74c3c; }
    .pill-medium { background: #f39c12; }
    .pill-low { background: #27ae60; }
    .pill-verylow { background: #3498db; }
    .muted { color: #999; font-style: italic; font-size: 9pt; }
    .pos { color: #27ae60; }
    .neg { color: #e74c3c; }
    .bar-wrap { width: 100%; height: 10px; background: #f0f0f0; border: 1px solid #e0e0e0; border-radius: 3px; }
    .bar { height: 100%; border-radius: 3px; }
    .swatch { display: inline-block; width: 12px; height: 12px; border-radius: 2px; vertical-align: middle; }
    .cover { text-align: center; padding-top: 2cm; }
    .cover h1 { font-size: 28pt; margin-bottom: 8px; }
    .cover .subtitle { color: #888; font-size: 14pt; margin-bottom: 24px; }
    .cover .period { color: #555; font-size: 12pt; margin-bottom: 8px; }
    .cover .generated { color: #999; font-size: 9pt; margin-top: 24px; }
    .page-break { page-break-after: always; }
    .footer { position: fixed; bottom: -1cm; left: 0; right: 0; text-align: center; font-size: 8pt; color: #999; }
</style>
</head>
<body>

{{-- Cover page --}}
<div class="cover">
    <h1>{{ $corpName }}</h1>
    <div class="subtitle">[{{ $report->corporation_id }}]</div>
    <h2 style="border: 0; color: #333;">Quarterly Report</h2>
    <div class="period"><strong>Period:</strong> {{ $report->date_from }} to {{ $report->date_to }}</div>
    <div class="generated">Generated {{ $report->created_at }}</div>
</div>

<div class="page-break"></div>

<h1>Quarterly Wallet Report</h1>
<div class="meta">
    <div><strong>Corporation:</strong> {{ $corpName }} (ID: {{ $report->corporation_id }})</div>
    <div><strong>Period:</strong> {{ $report->date_from }} to {{ $report->date_to }}</div>
    <div><strong>Generated:</strong> {{ $report->created_at }}</div>
</div>

@include('corpwalletmanager::reports.pdf._partials', ['kind' => 'quarterly'])

<div class="footer">Generated by Corp Wallet Manager [CWM] &middot; {{ $report->created_at }}</div>

</body>
</html>
